//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingDetail()
        {
            this.AdminTables = new HashSet<AdminTable>();
        }
    
        public int BookingID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string CarNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> BookedFrom { get; set; }
        public Nullable<System.DateTime> BookedTo { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminTable> AdminTables { get; set; }
    }
}
