//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public string CarNo { get; set; }
        public string CarName { get; set; }
        public string FuelType { get; set; }
        public string AirConditioning { get; set; }
        public string TransmissionType { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string CarType { get; set; }
        public Nullable<System.DateTime> YearofManufacture { get; set; }
        public Nullable<int> FullDayPrice { get; set; }
        public Nullable<int> HalfDayPrice { get; set; }
        public string CarImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
